<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="coverlet.collector">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="NetArchTest.Rules" />
    <PackageReference Include="xunit.v3" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="../../src/Contracts/CommerceFlow.Contracts/CommerceFlow.Contracts.csproj" />
    <ProjectReference Include="../../src/Sales/Sales.Domain/Sales.Domain.csproj" />
    <ProjectReference Include="../../src/Sales/Sales.Application/Sales.Application.csproj" />
    <ProjectReference Include="../../src/Sales/Sales.Infrastructure/Sales.Infrastructure.csproj" />
    <ProjectReference Include="../../src/Inventory/Inventory.Domain/Inventory.Domain.csproj" />
    <ProjectReference Include="../../src/Inventory/Inventory.Application/Inventory.Application.csproj" />
    <ProjectReference Include="../../src/Inventory/Inventory.Infrastructure/Inventory.Infrastructure.csproj" />
  </ItemGroup>
</Project>
