<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="coverlet.collector">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="System.IdentityModel.Tokens.Jwt" />
    <PackageReference Include="xunit.v3" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="../../src/Identity/CommerceFlow.Identity.Api/CommerceFlow.Identity.Api.csproj" />
    <ProjectReference Include="../../src/Inventory/Inventory.Domain/Inventory.Domain.csproj" />
    <ProjectReference Include="../../src/Sales/Sales.Domain/Sales.Domain.csproj" />
  </ItemGroup>
</Project>
