apiVersion: v1
kind: ConfigMap
metadata:
  name: commerceflow-config
data:
  ASPNETCORE_ENVIRONMENT: Production
  ASPNETCORE_URLS: http://+:8080
  Jwt__Issuer: commerceflow.identity
  Jwt__Audience: commerceflow.apis
  Services__InventoryBaseUrl: http://inventory:8080/
  RabbitMq__Host: rabbitmq.example.internal
  RabbitMq__Port: "5671"
  RabbitMq__UseTls: "true"
  RabbitMq__Username: commerceflow
  RabbitMq__VirtualHost: commerceflow
  OTEL_EXPORTER_OTLP_ENDPOINT: http://otel-collector.observability:4317
  OTEL_EXPORTER_OTLP_PROTOCOL: grpc
  OTEL_RESOURCE_ATTRIBUTES: deployment.environment=production,service.namespace=commerceflow
  ReverseProxy__Clusters__identity__Destinations__primary__Address: http://identity:8080
  ReverseProxy__Clusters__sales__Destinations__primary__Address: http://sales:8080
  ReverseProxy__Clusters__inventory__Destinations__primary__Address: http://inventory:8080
